// Automatically generated by api/generator/api.gen.go, DO NOT EDIT manually
// Package api implements Register method for fiber
package api

import (
	"encoding/json"

	"github.com/gofiber/fiber/v2"
	"github.com/kodflow/fizzbuzz/api/internal/api/fizzbuzz"
	"github.com/kodflow/fizzbuzz/api/internal/api/metrics"
	"github.com/kodflow/fizzbuzz/api/internal/api/status"
	"github.com/kodflow/fizzbuzz/api/internal/docs"
	"github.com/swaggo/swag"
)

func init() {
	json.Unmarshal([]byte(doc), Mapping)
}

// API represents a collection of HTTP endpoints grouped by namespace and version.
var (
	Endpoints map[string]fiber.Handler = map[string]func(*fiber.Ctx) error{
		"fizzbuzz.FizzBuzz":  fizzbuzz.FizzBuzz,
		"metrics.Statistics": metrics.Statistics,
		"status.HealthCheck": status.HealthCheck,
		"status.IP":          status.IP,
		"metrics.Counter":    metrics.Counter,
	}
	Mapping = &docs.Swagger{}
	doc, _  = swag.ReadDoc()
)
