version: '3'

silent: true

tasks:
  default:
    cmds:
      - task -l

  test:
    desc: Lancer les tests Go avec gotestsum
    cmds:
      - gotestsum -f github-actions -- -v $(go list ./... | grep -vE "vendor") -coverprofile=coverage.out -covermode=atomic

  build:bin:
    desc: Construire les binaires Go
    cmds:
      - CGO_ENABLED=0 go build -trimpath -buildvcs=false -tags netgo -ldflags "-s -w -extldflags '-static'" -o .build/fizzbuzz api/fizzbuzz/main.go
      - .build/$(basename $(pwd))
  
  deploy:local:
    dir: deploy/local
    desc: Déployer l'application en local
    cmds:
      - terraform init -upgrade
      - terraform apply -auto-approve
    